#!/bin/sh
# vim: ts=4 sts=4 sw=4 expandtab

list_all_disks() {
    fdisk -l /dev/[sv]d? | egrep '^Disk /' | cut -d " " -f 5,2
}

get_small_disks() {
    list_all_disks | sort -k2n | head -2 | cut -d : -f 1 | tr '\n' ' '
}

get_small_disks
